version: '3.9'
  
services:
  backend:
    build:
      context: ./Backend
    container_name: backend-app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}

  frontend:
    build:
      context: ./test
    container_name: frontend-app
    ports:
      - "5173:5173"
